version: '3.7'

services:

  # Nginx, overnet & frontend & backend, ports 80 & 443 & 15432 (postgresql) & 16379 (redis)
  app-nginx:
    image: your-app-nginx-image
    depends_on:
      - postgres
      - redis
      - server
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 30s
    networks:
      - overnet
    ports:
      - "80:80"
      - "443:443"
      - "15432:5432"
      - "16379:6379"

  # PostgreSQL, backend ,expose 5432
  app-postgres:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    networks:
      - overnet
    volumes:
      - data-postgres:/var/lib/postgresql/data

  # Redis, backend, expose 6379
  app-redis:
    image: redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s
    networks:
      - overnet
    volumes:
      - data-redis:/data

  # KBS, frontend & backend, expose 8080
  app-server:
    image: your-app-server-image
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 30s
    networks:
      - overnet
    volumes:
      - data-server:/app/data

networks:
  overnet:
    external: true
    name: overnet

volumes:
  data-postgres:
  data-redis:
  data-server:
